"""
The newsletter confirmation mail, and the transport under it.

Double opt-in has no other exit. `confirmed_at` is set by exactly one code
path — someone clicking the link in this email — and the send job filters on
that column, so every defect here presents identically to a working system
with no subscribers. These tests exist because that failure is silent.

Three properties are worth more than the rest:

  * The template substitutes every variable it declares, and escapes them.
  * A delivery failure leaves `confirmation_sent_at` NULL rather than lying.
  * `_send_confirmation` never raises, whatever the transport does. The
    endpoint above it must return the same 202 to every caller, and an
    exception escaping here would make the response vary with the recipient —
    the enumeration oracle the module was rewritten to close.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from app.core.config import Settings
from app.core.mail import (
    BrevoTransport,
    ConsoleTransport,
    MailDeliveryError,
    MailMessage,
    NullTransport,
)
from app.emails import NEWSLETTER_CONFIRMATION_SUBJECT, TemplateError, render
from app.modules.newsletter import router as nl

# --- The generated template ------------------------------------------------


def test_template_is_present_and_renders() -> None:
    """Guards the packaging failure in particular: the .html is generated by
    supabase/templates/build.mjs and only reaches a deployed instance because
    of the package-data entry in pyproject.toml."""
    html = render("newsletter_confirmation", ConfirmURL="https://x.test/c?token=abc", Frequency="weekly")
    assert "https://x.test/c?token=abc" in html
    assert "weekly" in html
    assert "{{" not in html


def test_confirm_url_is_the_href_not_just_text() -> None:
    """A URL that appears only as visible text is a link the recipient has to
    copy by hand, which is where a confirmation flow loses people."""
    html = render("newsletter_confirmation", ConfirmURL="https://x.test/c", Frequency="daily")
    assert 'href="https://x.test/c"' in html


def test_ampersands_in_the_url_are_escaped() -> None:
    """A raw `&` in an href is invalid HTML and some clients truncate the URL
    at it, which silently drops the token."""
    html = render(
        "newsletter_confirmation", ConfirmURL="https://x.test/c?token=a&next=b", Frequency="daily"
    )
    assert "token=a&amp;next=b" in html
    assert "token=a&next=b" not in html


def test_a_value_that_looks_like_markup_cannot_become_markup() -> None:
    html = render(
        "newsletter_confirmation", ConfirmURL="https://x.test/c", Frequency="<script>x</script>"
    )
    assert "<script>" not in html
    assert "&lt;script&gt;" in html


def test_missing_variable_raises_rather_than_shipping_a_placeholder() -> None:
    with pytest.raises(TemplateError, match="Frequency"):
        render("newsletter_confirmation", ConfirmURL="https://x.test/c")


def test_unknown_variable_raises() -> None:
    """Catches the rename that leaves the template reading the old name."""
    with pytest.raises(TemplateError, match="Nope"):
        render(
            "newsletter_confirmation",
            ConfirmURL="https://x.test/c",
            Frequency="daily",
            Nope="x",
        )


# --- Link construction -----------------------------------------------------


def test_confirm_url_points_at_the_site_not_the_api(monkeypatch: pytest.MonkeyPatch) -> None:
    """The API's own /confirm answers with JSON. A subscriber who lands there
    sees a white page with a brace on it."""
    monkeypatch.setattr(nl.settings, "SITE_URL", "https://pickdforyou.com")
    assert nl._confirm_url("tok123").startswith("https://pickdforyou.com/newsletter/confirm?")


def test_confirm_url_percent_encodes_the_token(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(nl.settings, "SITE_URL", "https://pickdforyou.com")
    assert "token=a%2Bb%3Dc" in nl._confirm_url("a+b=c")


# --- _send_confirmation ----------------------------------------------------


class _Recorder:
    def __init__(self) -> None:
        self.sent: list[MailMessage] = []

    async def send(self, message: MailMessage) -> None:
        self.sent.append(message)


class _Broken:
    async def send(self, message: MailMessage) -> None:
        raise MailDeliveryError("nope")


class _Exploding:
    async def send(self, message: MailMessage) -> None:
        raise RuntimeError("something nobody predicted")


async def test_send_confirmation_hands_the_transport_a_complete_message(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    rec = _Recorder()
    monkeypatch.setattr(nl, "get_transport", lambda: rec)
    monkeypatch.setattr(nl.settings, "SITE_URL", "https://pickdforyou.com")

    assert await nl._send_confirmation("reader@example.com", "tok123", "weekly") is True

    (msg,) = rec.sent
    assert msg.to == "reader@example.com"
    assert msg.subject == NEWSLETTER_CONFIRMATION_SUBJECT
    assert "tok123" in msg.html
    # The text part is not optional: a message with no plain-text alternative
    # scores worse with filters and is empty in a plain-text client.
    assert "tok123" in msg.text


async def test_cadence_is_rendered_in_english_not_as_a_column_value(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    rec = _Recorder()
    monkeypatch.setattr(nl, "get_transport", lambda: rec)

    await nl._send_confirmation("reader@example.com", "tok", "deals_only")

    (msg,) = rec.sent
    assert "deals only" in msg.html
    assert "deals_only" not in msg.html


async def test_delivery_failure_is_reported_as_false_not_raised(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(nl, "get_transport", lambda: _Broken())
    assert await nl._send_confirmation("reader@example.com", "tok", "daily") is False


async def test_an_unexpected_exception_is_also_contained(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`except MailDeliveryError` alone would let a bug in a transport escape
    into the endpoint and turn one recipient's 202 into a 500."""
    monkeypatch.setattr(nl, "get_transport", lambda: _Exploding())
    assert await nl._send_confirmation("reader@example.com", "tok", "daily") is False


async def test_the_address_is_not_written_to_the_log_on_failure(
    monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture
) -> None:
    """An address that never confirms did not consent to being recorded in
    plain text in a log aggregator."""
    monkeypatch.setattr(nl, "get_transport", lambda: _Broken())
    with caplog.at_level("WARNING"):
        await nl._send_confirmation("private@example.com", "tok", "daily")
    assert "private@example.com" not in caplog.text


# --- Brevo transport -------------------------------------------------------


class _FakeResponse:
    def __init__(self, status_code: int, text: str = "") -> None:
        self.status_code = status_code
        self.text = text


class _FakeClient:
    """Stands in for httpx.AsyncClient, which BrevoTransport constructs itself."""

    last_call: dict[str, object] = {}

    def __init__(self, response: _FakeResponse) -> None:
        self._response = response

    def __call__(self, **kwargs: object) -> _FakeClient:
        return self

    async def __aenter__(self) -> _FakeClient:
        return self

    async def __aexit__(self, *exc: object) -> None:
        return None

    async def post(self, url: str, **kwargs: object) -> _FakeResponse:
        type(self).last_call = {"url": url, **kwargs}
        return self._response


def _brevo() -> BrevoTransport:
    return BrevoTransport(
        api_key="key-abc", sender_email="hello@x.test", sender_name="PickDForYou", reply_to=""
    )


def _message() -> MailMessage:
    return MailMessage(to="a@b.test", subject="s", html="<p>h</p>", text="t")


async def test_brevo_uses_the_api_key_header_not_a_bearer_token(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Brevo rejects `Authorization: Bearer`, and the resulting 401 reads like
    a bad key rather than a wrong scheme — an hour lost, every time."""
    fake = _FakeClient(_FakeResponse(201))
    monkeypatch.setattr("app.core.mail.httpx.AsyncClient", fake)

    await _brevo().send(_message())

    headers = _FakeClient.last_call["headers"]
    assert isinstance(headers, dict)
    assert headers["api-key"] == "key-abc"
    assert "Authorization" not in headers


async def test_brevo_omits_reply_to_when_unset(monkeypatch: pytest.MonkeyPatch) -> None:
    """An empty replyTo object is a 400 from Brevo, not an ignored field."""
    fake = _FakeClient(_FakeResponse(201))
    monkeypatch.setattr("app.core.mail.httpx.AsyncClient", fake)

    await _brevo().send(_message())

    body = _FakeClient.last_call["json"]
    assert isinstance(body, dict)
    assert "replyTo" not in body


@pytest.mark.parametrize(
    ("status", "fragment"),
    [
        (401, "BREVO_API_KEY"),
        (402, "out of credits"),
        (429, "rate-limited"),
        (500, "500"),
    ],
)
async def test_brevo_failures_name_the_cause(
    monkeypatch: pytest.MonkeyPatch, status: int, fragment: str
) -> None:
    fake = _FakeClient(_FakeResponse(status, "detail"))
    monkeypatch.setattr("app.core.mail.httpx.AsyncClient", fake)

    with pytest.raises(MailDeliveryError, match=fragment):
        await _brevo().send(_message())


@pytest.mark.parametrize("status", [200, 201, 202])
async def test_brevo_accepts_every_success_status(
    monkeypatch: pytest.MonkeyPatch, status: int
) -> None:
    """Brevo documents 201 for this endpoint and returns 202 for some
    configurations. Checking `== 201` would fail on a message that was sent."""
    monkeypatch.setattr("app.core.mail.httpx.AsyncClient", _FakeClient(_FakeResponse(status)))
    await _brevo().send(_message())


# --- The other two transports ----------------------------------------------


async def test_console_transport_logs_the_link(caplog: pytest.LogCaptureFixture) -> None:
    """Reading the confirm URL out of the log is the only way to exercise
    double opt-in locally without a provider key."""
    with caplog.at_level("INFO"):
        await ConsoleTransport().send(
            MailMessage(to="a@b.test", subject="s", html='<a href="https://x.test/c?t=1">go</a>', text="t")
        )
    assert "https://x.test/c?t=1" in caplog.text


async def test_null_transport_is_silent() -> None:
    assert await NullTransport().send(_message()) is None


# --- Configuration guards --------------------------------------------------


def _settings(**overrides: object) -> Settings:
    base: dict[str, object] = {
        "_env_file": None,
        "SUPABASE_JWT_SECRET": "x" * 40,
    }
    return Settings(**{**base, **overrides})  # type: ignore[arg-type]


def test_console_transport_is_refused_in_production() -> None:
    """It writes single-use confirmation links to the log, and a production
    log outlives the 24 hours those links are meant to."""
    with pytest.raises(ValidationError, match="console"):
        _settings(ENVIRONMENT="production", MAIL_PROVIDER="console")


def test_disabled_transport_is_allowed_in_production() -> None:
    """Silence is a defensible production state — it is what the code did
    before this transport existed."""
    assert _settings(ENVIRONMENT="production", MAIL_PROVIDER="disabled").MAIL_PROVIDER == "disabled"


def test_brevo_without_a_key_fails_at_startup_not_at_the_first_subscriber() -> None:
    with pytest.raises(ValidationError, match="BREVO_API_KEY"):
        _settings(MAIL_PROVIDER="brevo", BREVO_API_KEY="")


def test_brevo_with_a_key_is_accepted() -> None:
    assert _settings(MAIL_PROVIDER="brevo", BREVO_API_KEY="k").MAIL_PROVIDER == "brevo"


def test_site_url_trailing_slash_is_normalised() -> None:
    """Or every link builder concatenates its way to a double slash, which
    some mail scanners rewrite and some proxies reject."""
    assert _settings(SITE_URL="https://x.test/").SITE_URL == "https://x.test"
